let countryName = {
  'Afghanistan': 'Афганістан',
  'Albania': 'Албанія',
  'Algeria': 'Алжир',
  'Andorra': 'Андорра',
  'Anguilla': 'Анґілла',
  'Antarctica': 'Антарктика',
  'Antigua And Barbuda': 'Антиґуа і Барбуда',
  'Argentina': 'Аргентина',
  'Armenia': 'Вірменія',
  'Aruba': 'Аруба',
  'Australia': 'Австралія',
  'Austria': 'Австрія',
  'Azerbaijan': 'Азербайджан',
  'Bahamas': 'Багами',
  'Bahrain': 'Бахрейн',
  'Bangladesh': 'Бангладеш',
  'Barbados': 'Барбадос',
  'Belarus': 'Білорусь',
  'Belarussia': 'Білорусія',
  'Belgium': 'Бельгія',
  'Belize': 'Беліз',
  'Benin': 'Бенін',
  'Bermuda': 'Бермуда',
  'Bhutan': 'Бутан',
  'Bolivia': 'Болівія',
  'Bosnia and Herzegovina': 'Боснія і Герцеґовина',
  'Botswana': 'Ботсвана',
  'Brazil': 'Бразилія',
  'Brunei Darussalam': 'Бруней Даруссалам',
  'Bulgaria': 'Болгарія',
  'Burkina Faso': 'Буркіна Фасо',
  'Burundi': 'Бурунді',
  'Cambodia': 'Камбоджа',
  'Cameroon': 'Камерун',
  'Canada': 'Канада',
  'Cape Verde': 'Капо Верде',
  'Cayman Islands': 'Кайманові острови',
  'Central African Republic': 'Центральна Африканська Республіка',
  'Chad': 'Чад',
  'Chile': 'Чилі',
  'China': 'Китай',
  'Christmas Island': 'Різдвяні острови',
  'Colombia': 'Колумбія',
  'Comoros': 'Комори',
  'Congo': 'Конго',
  'Cook Islands': 'Кука, острови',
  'Costa Rica': 'Ко ста Ріка',
  'Croatia': 'Хорватія',
  'Cyprus': 'Кіпр',
  'Czech Republic': 'Че ська Респу бліка',
  'Denmark': 'Данія',
  'Djibouti': 'Джибу ті',
  'Dominica': 'Домініка',
  'Dominican Republic': 'Домініка нська Республіка',
  'East Timor': 'Східний Тимор',
  'Ecuador': 'Еквадор',
  'Egypt': 'Єгипет',
  'El Salvador': 'Ель Сальвадор',
  'England': 'Англія',
  'Equatorial Guinea': 'Екваторіальна Ґвінея',
  'Eritrea': 'Еритрея',
  'Espana': 'Іспанія',
  'Estonia': 'Естонія',
  'Ethiopia': 'Ефіопія',
  'Falkland Islands': 'Фолклендські острови',
  'Faroe Islands': 'Фарерські острови ',
  'Fiji': 'Фіджі',
  'Finland': 'Фінляндія',
  'France': 'Франція',
  'Gabon': 'Ґабон',
  'Gambia': 'Ґамбія',
  'Georgia': 'Грузія',
  'Germany': 'Німеччина',
  'Ghana': 'Ґана',
  'Gibraltar': 'Ґібралтар',
  'Great Britain': 'Велика Британія',
  'Greece': 'Греція',
  'Greenland': 'Ґренландія',
  'Grenada': 'Ґренада',
  'Guadeloupe': 'Ґваделупа',
  'Guam': 'Ґуам',
  'Guatemala': 'Ґватемала',
  'Guinea': 'Ґвінея',
  'Guinea-Bissau': 'Ґвінея-Біссау',
  'Guyana': 'Ґвіа  на',
  'Haiti': 'Гаїті',
  'Honduras': 'Гондурас',
  'Hong Kong': 'Гон-Конґ',
  'Hungary': 'Угорщина',
  'Iceland': 'Ісландія',
  'India': 'Індія',
  'Indonesia': 'Індонезія',
  'Iran': 'Іран',
  'Iraq': 'Ірак',
  'Ireland': 'Ірландія',
  'Israel': 'Ізраїль',
  'Italy': 'Італія',
  'Jamaica': 'Ямайка',
  'Japan': 'Японія',
  'Jordan': 'Іорданія',
  'Kazakhstan': 'Казахстан',
  'Kenya': 'Кенія',
  'Kiribati': 'Кірібаті',
  'Korea, Republic of': 'Корейська Республіка',
  'Korea (South)': 'Корея (Південна)',
  'Kuwait': 'Кувейт',
  'Kyrgyzstan': 'Киргизстан',
  'Latvia': 'Латвія',
  'Lebanon': 'Ливан',
  'Lesotho': 'Лесото',
  'Liberia': 'Ліберія',
  'Liechtenstein': 'Ліхтенштейн',
  'Lithuania': 'Литва',
  'Luxembourg': 'Люксембург',
  'Macau': 'Макао',
  'Macedonia': 'Македонія',
  'Madagascar': 'Мадагаскар',
  'Malawi': 'Малаві',
  'Malaysia': 'Малайзія',
  'Maldives': 'Мальдиви',
  'Mali': 'Малі',
  'Malta': 'Мальта',
  'Marshall Islands': 'Маршаллові острови',
  'Martinique': 'Мартиніка',
  'Mauritania': 'Мавританія',
  'Mexico': 'Мексика',
  'Monaco': 'Монако',
  'Mongolia': 'Монголія',
  'Morocco': 'Марокко',
  'Mozambique': 'Мозамбік',
  'Namibia': 'Намібія',
  'Nauru': 'Науру',
  'Nepal': 'Непал',
  'Netherlands': 'Нідерланди',
  'New Caledonia': 'Нова Каледонія',
  'New Zealand': 'Нова Зеландія',
  'Nicaragua': 'Нікарагуа',
  'Nigeria': 'Нігерія',
  'Northern Ireland': 'Північна Ірландія',
  'Norway': 'Норвегія',
  'Oman': 'Оман',
  'Pakistan': 'Пакістан',
  'Palau': 'Палау',
  'Panama': 'Панама',
  'Papua New Guinea': 'Папуа Нова Ґвінея',
  'Paraguay': 'Парагвай',
  'Peru': 'Перу',
  'Philippines': 'Філіппіни',
  'Poland': 'Польща',
  'Portugal': 'Португалія',
  'Puerto Rico': 'Пуерто Ріко',
  'Qatar': 'Катар',
  'Reunion': 'Реуніон',
  'Romania': 'Румунія',
  'Russia': 'Росія',
  'Russian Federation': 'Російська Федерація',
  'Rwanda': 'Руанда',
  'Saint Lucia': 'Санта Люсія',
  'Saint Vincent and the Grenadines': 'Сент Вінсент і Ґренадіни',
  'Samoa (Independent)': 'Самоа',
  'San Marino': 'Сан Маріно',
  'Saudi Arabia': 'Саудівська Аравія',
  'Scotland': 'Шотландія',
  'Senegal': 'Сенегал',
  'Seychelles': 'Сейшели',
  'Sierra Leone': 'Сьєрра Леоне',
  'Singapore': 'Сингапур',
  'Slovakia': 'Словаччина',
  'Slovenia': 'Словенія',
  'Solomon Islands': 'Соломонові острови',
  'Somalia': 'Сомалі',
  'South Africa': 'Південна Африка',
  'South Korea': 'Південна Корея',
  'Spain': 'Іспанія',
  'Sri Lanka': 'Шрі Ланка',
  'Suriname': 'Сурінам',
  'Swaziland': 'Свазиленд',
  'Sweden': 'Швеція',
  'Switzerland': 'Швейцарія',
  'Taiwan': 'Тайвань',
  'Tajikistan': 'Таджикістан',
  'Tanzania': 'Танзанія',
  'Thailand': 'Таїланд',
  'Togo': 'Тоґо',
  'Tonga': 'Тонґа',
  'Trinidad': 'Тринідад',
  'Trinidad and Tobago': 'Тринідад і Тобаґо',
  'Tunisia': 'Туніс',
  'Turkey': 'Туреччина',
  'Turkmenistan': 'Туркменістан',
  'Tuvalu': 'Тувалу',
  'Uganda': 'Уґанда',
  'Ukraine': 'Україна',
  'United Arab Emirates': "Об'єднані Арабські Емірати",
  'United Kingdom': "Об'єднане Королівство",
  'United States of America': 'Сполучені Штати Америки',
  'United States': 'США',
  'Uruguay': 'Уругвай',
  'USA': 'США',
  'Uzbekistan': 'Узбекістан',
  'Vanuatu': 'Вануату',
  'Venezuela': 'Венесуела',
  'Viet Nam': "В'єтнам",
  'Wales': 'Уельс',
  'Western Sahara': 'Західна Сахара',
  'Yemen': 'Ємен',
  'Yugoslavia': 'Югославія',
  'Zambia': 'Замбія',
  'Zimbabwe': 'Зимбабве'
};